services:
  database:
    image: postgis/postgis:17-3.5-alpine
    container_name: db_postgis
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend_dietiestates
    restart: always
    depends_on:
      - database
    environment:
      DB_URL: jdbc:postgresql://database:5432/DietiEstates25?currentSchema=est,public
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: DE25@S3cr3t
      GOOGLE_CLIENT_SECRET: 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
      GITHUB_REDIRECT_URI: http://10.0.2.2:8080/api/v1/auth/github/callback
      GITHUB_CLIENT_SECRET: 794c1f3a9678cb24b4540bc39cef6dc50a3db4a3
      SENDGRID_API_KEY: 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
    ports:
      - "8080:8080"

volumes:
  db_data:
