services:
  database:
    image: postgis/postgis:17-3.5-alpine
    container_name: db_postgis
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
      - ../../DATABASE/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  backend:
    build: .
    container_name: backend_dietiestates
    depends_on:
      - database
    environment:
      DB_URL: jdbc:postgresql://database:5432/DietiEstates25?currentSchema=est,public
      DB_USER: postgres
      DB_PASSWORD: postgres
      JWT_SECRET: DE25@S3cr3t
      GOOGLE_CLIENT_SECRET: 
      GITHUB_REDIRECT_URI: http://10.0.2.2:8080/api/v1/auth/github/callback
      GITHUB_CLIENT_SECRET: 
      SENDGRID_API_KEY: 
    ports:
      - "8080:8080"

volumes:
  db_data:
